[package]
name = "pdf_render"
version = "0.1.0"
authors = ["Sebastian Köln <s3bk@protonmail.com>"]
edition = "2021"

[features]
unstable = []
embed = ["dep:rust-embed"]
glyphmatcher = ["dep:glyphmatcher"]

[[bench]]
name = "render"
harness = false

[dependencies.pdf]
default-features = false
features = ["cache", "dump"]
git = "https://github.com/pdf-rs/pdf"

[dependencies]
# pathfinder_renderer = { git = "https://github.com/servo/pathfinder" }
pathfinder_color.workspace = true
pathfinder_geometry.workspace = true
pathfinder_resources.workspace = true
pathfinder_content.workspace = true
log.workspace = true
font.workspace = true
pdf_encoding.workspace = true
itertools.workspace = true

rust-embed = { workspace = true, optional = true }

image.workspace = true
instant.workspace = true
custom_debug_derive.workspace = true
globalcache.workspace = true
istring.workspace = true
once_cell.workspace = true
serde_json.workspace = true
glyphmatcher = { workspace = true, optional = true }
vello_encoding.workspace = true
vello.workspace = true
backtrace.workspace = true

[dev-dependencies]
criterion.workspace = true
env_logger.workspace = true
