[package]
name = "pdf_vview"
version = "0.1.0"
authors = ["Sebastian Köln <s3bk@protonmail.com>"]
edition = "2021"

[features]
unstable = []

[dependencies.pdf]
git = "https://github.com/pdf-rs/pdf"
default-features = false
features = ["dump"]

[dependencies.pdf_render]
path = "../render"

[dependencies]
pathfinder_geometry.workspace = true
log.workspace = true

font.workspace = true
itertools.workspace = true

image.workspace = true
vello.workspace = true

winit.workspace = true
env_logger.workspace = true
pollster.workspace = true
clap.workspace = true

[dev-dependencies]
criterion.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "pdf_vview"
path = "bin/view.rs"
